CREATE TABLE "employee_profiles" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid,
	"employee_id" varchar(50) NOT NULL,
	"name" varchar(50) NOT NULL,
	"name_pinyin" varchar(100) NOT NULL,
	"name_en" varchar(50) NOT NULL,
	"gender" varchar(10) NOT NULL,
	"birth_date" date NOT NULL,
	"ethnicity" varchar(20) NOT NULL,
	"phone" varchar(20) NOT NULL,
	"native_place" varchar(100) NOT NULL,
	"political_status" varchar(20) NOT NULL,
	"department_id" uuid NOT NULL,
	"position" varchar(50) NOT NULL,
	"job_level" varchar(20) NOT NULL,
	"supervisor_id" uuid,
	"work_location" varchar(100) NOT NULL,
	"cost_center" varchar(50) NOT NULL,
	"entry_date" date NOT NULL,
	"regular_date" date NOT NULL,
	"contract_type" varchar(20) NOT NULL,
	"sign_date" date NOT NULL,
	"contract_period" varchar(30) NOT NULL,
	"renewal_remind" boolean DEFAULT false NOT NULL,
	"contract_file" varchar(500) DEFAULT '' NOT NULL,
	"education" jsonb,
	"work_history" jsonb,
	"project_exp" jsonb,
	"languages" jsonb,
	"certificates" jsonb,
	"skills" jsonb,
	"parent_names" varchar(100),
	"parent_phones" varchar(50),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "employee_profiles_user_id_unique" UNIQUE("user_id"),
	CONSTRAINT "employee_profiles_employee_id_unique" UNIQUE("employee_id")
);
